// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"

	"github.com/petergtz/pegomock"

	jobs "github.com/runatlantis/atlantis/server/jobs"
)

func AnyJobsJob() jobs.Job {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(jobs.Job))(nil)).Elem()))
	var nullValue jobs.Job
	return nullValue
}

func EqJobsJob(value jobs.Job) jobs.Job {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue jobs.Job
	return nullValue
}

func NotEqJobsJob(value jobs.Job) jobs.Job {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue jobs.Job
	return nullValue
}

func JobsJobThat(matcher pegomock.ArgumentMatcher) jobs.Job {
	pegomock.RegisterMatcher(matcher)
	var nullValue jobs.Job
	return nullValue
}
