// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	models "github.com/runatlantis/atlantis/server/events/models"
)

func AnyModelsCommitStatus() models.CommitStatus {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(models.CommitStatus))(nil)).Elem()))
	var nullValue models.CommitStatus
	return nullValue
}

func EqModelsCommitStatus(value models.CommitStatus) models.CommitStatus {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue models.CommitStatus
	return nullValue
}

func NotEqModelsCommitStatus(value models.CommitStatus) models.CommitStatus {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue models.CommitStatus
	return nullValue
}

func ModelsCommitStatusThat(matcher pegomock.ArgumentMatcher) models.CommitStatus {
	pegomock.RegisterMatcher(matcher)
	var nullValue models.CommitStatus
	return nullValue
}
