// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	command "github.com/runatlantis/atlantis/server/events/command"
)

func AnyPtrToCommandProjectResult() *command.ProjectResult {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*command.ProjectResult))(nil)).Elem()))
	var nullValue *command.ProjectResult
	return nullValue
}

func EqPtrToCommandProjectResult(value *command.ProjectResult) *command.ProjectResult {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *command.ProjectResult
	return nullValue
}

func NotEqPtrToCommandProjectResult(value *command.ProjectResult) *command.ProjectResult {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue *command.ProjectResult
	return nullValue
}

func PtrToCommandProjectResultThat(matcher pegomock.ArgumentMatcher) *command.ProjectResult {
	pegomock.RegisterMatcher(matcher)
	var nullValue *command.ProjectResult
	return nullValue
}
