// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	models "github.com/runatlantis/atlantis/server/events/models"
)

func AnyModelsCommandName() models.CommandName {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(models.CommandName))(nil)).Elem()))
	var nullValue models.CommandName
	return nullValue
}

func EqModelsCommandName(value models.CommandName) models.CommandName {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue models.CommandName
	return nullValue
}
