changelog:
  exclude:
    labels:
      - ignore-for-release
      - github-actions
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
        - feature
    - title: Provider AzureDevops
      labels:
        - provider/azuredevops
    - title: Provider Bitbucket
      labels:
        - provider/bitbucket
    - title: Provider GitHub
      labels:
        - provider/github
    - title: Provider GitLab
      labels:
        - provider/gitlab
    - title: Bug fixes 🐛
      labels:
        - bug
    - title: Security changes :lock:
      labels:
        - security
    - title: Documentation
      labels:
        - docs
        - website
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes 🔄
      labels:
        - "*"
