linters:
  enable:
  - errcheck
  - gochecknoinits
# We don't use goconst because it gives false positives in the tests.
#  - goconst
  - gofmt
  - revive
  - gosec
  - gosimple
  - ineffassign
  - staticcheck
  - typecheck
  - unconvert
  - unused
  - vet
  - vetshadow
run:
  timeout: 10m
