linters:
  enable:
  - deadcode
  - errcheck
  - gochecknoinits
# We don't use goconst because it gives false positives in the tests.
#  - goconst
  - gofmt
  - revive
  - gosec
  - gosimple
  - ineffassign
  - interfacer
  - staticcheck
  - structcheck
  - typecheck
  - unconvert
  - unused
  - varcheck
  - vet
  - vetshadow
