version: "2"

linters:
  enable:
    - errcheck
    - gochecknoinits
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unused
run:
  timeout: 10m
