linters-settings:
  misspell:
    locale: US

linters:
  enable:
  - errcheck
  - gochecknoinits
  - gofmt
  - gosec
  - gosimple
  - ineffassign
  - misspell
  - revive
  - staticcheck
  - typecheck
  - unconvert
  - unused
  - vet
  - vetshadow
run:
  timeout: 10m
