# Note: This file is only used for Atlantis local development
services:
  ngrok:
    image: ngrok/ngrok:latest@sha256:1d5daa80665b74694dc9804dd64a59da0defea910fe7799ab380e52483aeca1c
    ports:
      - 4040:4040
    command:
      - "http"
      - "atlantis:4141"
    env_file:
      - atlantis.env
    depends_on:
      - atlantis
  redis:
    image: redis:8.6-alpine@sha256:d146f83b1e0f02fc27c26a50cee39338c736674c5959db84363e6ae3cd9e02d2
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass test123
    volumes:
      - redis:/data
  atlantis:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4141:4141
    volumes:
      - ${HOME}/.ssh:/.ssh:ro
      - ${PWD}:/atlantis/src:ro
    # Contains the flags that atlantis uses in env var form
    env_file:
      - atlantis.env

volumes:
  redis:
    driver: local
