# Note: This file is only used for Atlantis local development
services:
  ngrok:
    image: ngrok/ngrok:latest@sha256:068852d1cf8b0c6f63cd1e8b7ebd42ece7b399458b9f1e93093c103cf992ccbf
    ports:
      - 4040:4040
    command:
      - "http"
      - "atlantis:4141"
    env_file:
      - atlantis.env
    depends_on:
      - atlantis
  redis:
    image: redis:8.6-alpine@sha256:81b6f81d6a6c5b9019231a2e8eb10085e3a139a34f833dcc965a8a959b040b72
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass test123
    volumes:
      - redis:/data
  atlantis:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4141:4141
    volumes:
      - ${HOME}/.ssh:/.ssh:ro
      - ${PWD}:/atlantis/src:ro
    # Contains the flags that atlantis uses in env var form
    env_file:
      - atlantis.env

volumes:
  redis:
    driver: local
