// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	models "github.com/runatlantis/atlantis/server/events/models"
)

func AnySliceOfModelsProjectLock() []models.ProjectLock {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*([]models.ProjectLock))(nil)).Elem()))
	var nullValue []models.ProjectLock
	return nullValue
}

func EqSliceOfModelsProjectLock(value []models.ProjectLock) []models.ProjectLock {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue []models.ProjectLock
	return nullValue
}

func NotEqSliceOfModelsProjectLock(value []models.ProjectLock) []models.ProjectLock {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue []models.ProjectLock
	return nullValue
}

func SliceOfModelsProjectLockThat(matcher pegomock.ArgumentMatcher) []models.ProjectLock {
	pegomock.RegisterMatcher(matcher)
	var nullValue []models.ProjectLock
	return nullValue
}
