// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/events (interfaces: URLGenerator)

package mocks

import (
	pegomock "github.com/petergtz/pegomock/v4"
	command "github.com/runatlantis/atlantis/server/events/command"
	"reflect"
	"time"
)

type MockURLGenerator struct {
	fail func(message string, callerSkip ...int)
}

func NewMockURLGenerator(options ...pegomock.Option) *MockURLGenerator {
	mock := &MockURLGenerator{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockURLGenerator) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockURLGenerator) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockURLGenerator) GenerateLockURL(lockID string) string {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockURLGenerator().")
	}
	_params := []pegomock.Param{lockID}
	_result := pegomock.GetGenericMockFrom(mock).Invoke("GenerateLockURL", _params, []reflect.Type{reflect.TypeOf((*string)(nil)).Elem()})
	var _ret0 string
	if len(_result) != 0 {
		if _result[0] != nil {
			_ret0 = _result[0].(string)
		}
	}
	return _ret0
}

func (mock *MockURLGenerator) GenerateProjectJobURL(ctx command.ProjectContext) (string, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockURLGenerator().")
	}
	_params := []pegomock.Param{ctx}
	_result := pegomock.GetGenericMockFrom(mock).Invoke("GenerateProjectJobURL", _params, []reflect.Type{reflect.TypeOf((*string)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var _ret0 string
	var _ret1 error
	if len(_result) != 0 {
		if _result[0] != nil {
			_ret0 = _result[0].(string)
		}
		if _result[1] != nil {
			_ret1 = _result[1].(error)
		}
	}
	return _ret0, _ret1
}

func (mock *MockURLGenerator) VerifyWasCalledOnce() *VerifierMockURLGenerator {
	return &VerifierMockURLGenerator{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockURLGenerator) VerifyWasCalled(invocationCountMatcher pegomock.InvocationCountMatcher) *VerifierMockURLGenerator {
	return &VerifierMockURLGenerator{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockURLGenerator) VerifyWasCalledInOrder(invocationCountMatcher pegomock.InvocationCountMatcher, inOrderContext *pegomock.InOrderContext) *VerifierMockURLGenerator {
	return &VerifierMockURLGenerator{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockURLGenerator) VerifyWasCalledEventually(invocationCountMatcher pegomock.InvocationCountMatcher, timeout time.Duration) *VerifierMockURLGenerator {
	return &VerifierMockURLGenerator{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockURLGenerator struct {
	mock                   *MockURLGenerator
	invocationCountMatcher pegomock.InvocationCountMatcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockURLGenerator) GenerateLockURL(lockID string) *MockURLGenerator_GenerateLockURL_OngoingVerification {
	_params := []pegomock.Param{lockID}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "GenerateLockURL", _params, verifier.timeout)
	return &MockURLGenerator_GenerateLockURL_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockURLGenerator_GenerateLockURL_OngoingVerification struct {
	mock              *MockURLGenerator
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockURLGenerator_GenerateLockURL_OngoingVerification) GetCapturedArguments() string {
	lockID := c.GetAllCapturedArguments()
	return lockID[len(lockID)-1]
}

func (c *MockURLGenerator_GenerateLockURL_OngoingVerification) GetAllCapturedArguments() (_param0 []string) {
	_params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(_params) > 0 {
		if len(_params) > 0 {
			_param0 = make([]string, len(c.methodInvocations))
			for u, param := range _params[0] {
				_param0[u] = param.(string)
			}
		}
	}
	return
}

func (verifier *VerifierMockURLGenerator) GenerateProjectJobURL(ctx command.ProjectContext) *MockURLGenerator_GenerateProjectJobURL_OngoingVerification {
	_params := []pegomock.Param{ctx}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "GenerateProjectJobURL", _params, verifier.timeout)
	return &MockURLGenerator_GenerateProjectJobURL_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockURLGenerator_GenerateProjectJobURL_OngoingVerification struct {
	mock              *MockURLGenerator
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockURLGenerator_GenerateProjectJobURL_OngoingVerification) GetCapturedArguments() command.ProjectContext {
	ctx := c.GetAllCapturedArguments()
	return ctx[len(ctx)-1]
}

func (c *MockURLGenerator_GenerateProjectJobURL_OngoingVerification) GetAllCapturedArguments() (_param0 []command.ProjectContext) {
	_params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(_params) > 0 {
		if len(_params) > 0 {
			_param0 = make([]command.ProjectContext, len(c.methodInvocations))
			for u, param := range _params[0] {
				_param0[u] = param.(command.ProjectContext)
			}
		}
	}
	return
}
