// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/events (interfaces: JobIDGenerator)

package mocks

import (
	pegomock "github.com/petergtz/pegomock"
	"reflect"
	"time"
)

type MockJobIDGenerator struct {
	fail func(message string, callerSkip ...int)
}

func NewMockJobIDGenerator(options ...pegomock.Option) *MockJobIDGenerator {
	mock := &MockJobIDGenerator{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockJobIDGenerator) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockJobIDGenerator) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockJobIDGenerator) GenerateJobID() string {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockJobIDGenerator().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("GenerateJobID", params, []reflect.Type{reflect.TypeOf((*string)(nil)).Elem()})
	var ret0 string
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(string)
		}
	}
	return ret0
}

func (mock *MockJobIDGenerator) VerifyWasCalledOnce() *VerifierMockJobIDGenerator {
	return &VerifierMockJobIDGenerator{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockJobIDGenerator) VerifyWasCalled(invocationCountMatcher pegomock.InvocationCountMatcher) *VerifierMockJobIDGenerator {
	return &VerifierMockJobIDGenerator{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockJobIDGenerator) VerifyWasCalledInOrder(invocationCountMatcher pegomock.InvocationCountMatcher, inOrderContext *pegomock.InOrderContext) *VerifierMockJobIDGenerator {
	return &VerifierMockJobIDGenerator{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockJobIDGenerator) VerifyWasCalledEventually(invocationCountMatcher pegomock.InvocationCountMatcher, timeout time.Duration) *VerifierMockJobIDGenerator {
	return &VerifierMockJobIDGenerator{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockJobIDGenerator struct {
	mock                   *MockJobIDGenerator
	invocationCountMatcher pegomock.InvocationCountMatcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockJobIDGenerator) GenerateJobID() *MockJobIDGenerator_GenerateJobID_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "GenerateJobID", params, verifier.timeout)
	return &MockJobIDGenerator_GenerateJobID_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockJobIDGenerator_GenerateJobID_OngoingVerification struct {
	mock              *MockJobIDGenerator
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockJobIDGenerator_GenerateJobID_OngoingVerification) GetCapturedArguments() {
}

func (c *MockJobIDGenerator_GenerateJobID_OngoingVerification) GetAllCapturedArguments() {
}
