// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/events (interfaces: AzureDevopsPullGetter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_azuredevops_pull_getter.go -package=mocks github.com/runatlantis/atlantis/server/events AzureDevopsPullGetter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	azuredevops "github.com/drmaxgit/go-azuredevops/azuredevops"
	models "github.com/runatlantis/atlantis/server/events/models"
	logging "github.com/runatlantis/atlantis/server/logging"
	gomock "go.uber.org/mock/gomock"
)

// MockAzureDevopsPullGetter is a mock of AzureDevopsPullGetter interface.
type MockAzureDevopsPullGetter struct {
	ctrl     *gomock.Controller
	recorder *MockAzureDevopsPullGetterMockRecorder
	isgomock struct{}
}

// MockAzureDevopsPullGetterMockRecorder is the mock recorder for MockAzureDevopsPullGetter.
type MockAzureDevopsPullGetterMockRecorder struct {
	mock *MockAzureDevopsPullGetter
}

// NewMockAzureDevopsPullGetter creates a new mock instance.
func NewMockAzureDevopsPullGetter(ctrl *gomock.Controller) *MockAzureDevopsPullGetter {
	mock := &MockAzureDevopsPullGetter{ctrl: ctrl}
	mock.recorder = &MockAzureDevopsPullGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAzureDevopsPullGetter) EXPECT() *MockAzureDevopsPullGetterMockRecorder {
	return m.recorder
}

// GetPullRequest mocks base method.
func (m *MockAzureDevopsPullGetter) GetPullRequest(logger logging.SimpleLogging, repo models.Repo, pullNum int) (*azuredevops.GitPullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequest", logger, repo, pullNum)
	ret0, _ := ret[0].(*azuredevops.GitPullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequest indicates an expected call of GetPullRequest.
func (mr *MockAzureDevopsPullGetterMockRecorder) GetPullRequest(logger, repo, pullNum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequest", reflect.TypeOf((*MockAzureDevopsPullGetter)(nil).GetPullRequest), logger, repo, pullNum)
}
