// Copyright 2025 The Atlantis Authors
// SPDX-License-Identifier: Apache-2.0

package oidc_test

import (
	"encoding/base64"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/runatlantis/atlantis/server/logging"
	"github.com/runatlantis/atlantis/server/oidc"
	. "github.com/runatlantis/atlantis/testing"
)

func newTestLogger(t *testing.T) logging.SimpleLogging {
	t.Helper()
	return logging.NewNoopLogger(t)
}

func findCookie(cookies []*http.Cookie, name string) *http.Cookie {
	for _, c := range cookies {
		if c.Name == name {
			return c
		}
	}
	return nil
}

func TestSessionManager_SetAndGetSession(t *testing.T) {
	logger := newTestLogger(t)
	sm := oidc.NewSessionManager([]byte("test-secret-32-characters-long!!"), false, "", logger)

	email := "user@example.com"

	w := httptest.NewRecorder()
	Ok(t, sm.SetSession(w, email))

	sessionCookie := findCookie(w.Result().Cookies(), "atlantis_oidc")
	Assert(t, sessionCookie != nil, "expected atlantis_oidc cookie to be set")
	Assert(t, sessionCookie.HttpOnly, "expected cookie to be HttpOnly")
	Equals(t, http.SameSiteLaxMode, sessionCookie.SameSite)

	r := httptest.NewRequest("GET", "/", nil)
	r.AddCookie(sessionCookie)

	got, err := sm.GetSession(r)
	Ok(t, err)
	Equals(t, email, got)
}

func TestSessionManager_GetSession_NoCookie(t *testing.T) {
	logger := newTestLogger(t)
	sm := oidc.NewSessionManager([]byte("test-secret-32-characters-long!!"), false, "", logger)

	r := httptest.NewRequest("GET", "/", nil)
	_, err := sm.GetSession(r)
	Assert(t, err != nil, "expected error when no cookie present")
}

func TestSessionManager_GetSession_TamperedCookie(t *testing.T) {
	logger := newTestLogger(t)
	sm := oidc.NewSessionManager([]byte("test-secret-32-characters-long!!"), false, "", logger)

	r := httptest.NewRequest("GET", "/", nil)
	r.AddCookie(&http.Cookie{
		Name:  "atlantis_oidc",
		Value: "tampered-value",
	})

	_, err := sm.GetSession(r)
	Assert(t, err != nil, "expected error for tampered cookie")
}

func TestSessionManager_GetSession_WrongSecret(t *testing.T) {
	logger := newTestLogger(t)
	sm1 := oidc.NewSessionManager([]byte("secret-one-32-characters-long!!"), false, "", logger)
	sm2 := oidc.NewSessionManager([]byte("secret-two-32-characters-long!!"), false, "", logger)

	w := httptest.NewRecorder()
	Ok(t, sm1.SetSession(w, "user@example.com"))

	r := httptest.NewRequest("GET", "/", nil)
	for _, c := range w.Result().Cookies() {
		r.AddCookie(c)
	}

	_, err := sm2.GetSession(r)
	Assert(t, err != nil, "expected error when verifying with wrong secret")
}

func TestSessionManager_ClearSession(t *testing.T) {
	logger := newTestLogger(t)
	sm := oidc.NewSessionManager([]byte("test-secret-32-characters-long!!"), false, "", logger)

	w := httptest.NewRecorder()
	sm.ClearSession(w)

	c := findCookie(w.Result().Cookies(), "atlantis_oidc")
	Assert(t, c != nil, "expected atlantis_oidc cookie in response")
	Equals(t, -1, c.MaxAge)
}

func TestSessionManager_CreateAndVerifyState(t *testing.T) {
	logger := newTestLogger(t)
	sm := oidc.NewSessionManager([]byte("test-secret-32-characters-long!!"), false, "", logger)

	w := httptest.NewRecorder()
	state, err := sm.CreateState(w)
	Ok(t, err)
	Assert(t, state != "", "expected non-empty state")

	r := httptest.NewRequest("GET", "/auth/callback?state="+state, nil)
	for _, c := range w.Result().Cookies() {
		r.AddCookie(c)
	}

	Ok(t, sm.VerifyState(r, state))
}

func TestSessionManager_VerifyState_Mismatch(t *testing.T) {
	logger := newTestLogger(t)
	sm := oidc.NewSessionManager([]byte("test-secret-32-characters-long!!"), false, "", logger)

	w := httptest.NewRecorder()
	_, err := sm.CreateState(w)
	Ok(t, err)

	r := httptest.NewRequest("GET", "/auth/callback", nil)
	for _, c := range w.Result().Cookies() {
		r.AddCookie(c)
	}

	err = sm.VerifyState(r, "wrong-state")
	Assert(t, err != nil, "expected error for mismatched state")
}

func TestSessionManager_AutoGeneratedSecret(t *testing.T) {
	logger := newTestLogger(t)
	sm := oidc.NewSessionManager(nil, false, "", logger)

	w := httptest.NewRecorder()
	Ok(t, sm.SetSession(w, "auto@example.com"))

	r := httptest.NewRequest("GET", "/", nil)
	for _, c := range w.Result().Cookies() {
		r.AddCookie(c)
	}

	got, err := sm.GetSession(r)
	Ok(t, err)
	Equals(t, "auto@example.com", got)
}

func TestSessionManager_CookieValueDoesNotContainEmail(t *testing.T) {
	logger := newTestLogger(t)
	sm := oidc.NewSessionManager([]byte("test-secret-32-characters-long!!"), false, "", logger)

	email := "sensitive-user@example.com"
	w := httptest.NewRecorder()
	Ok(t, sm.SetSession(w, email))

	c := findCookie(w.Result().Cookies(), "atlantis_oidc")
	Assert(t, c != nil, "expected atlantis_oidc cookie")
	Assert(t, !strings.Contains(c.Value, email), "cookie value contains email in plaintext")
	if decoded, err := base64.RawURLEncoding.DecodeString(c.Value); err == nil {
		Assert(t, !strings.Contains(string(decoded), email), "decoded cookie value contains email in plaintext")
	}
}

func TestSessionManager_SecureCookie(t *testing.T) {
	logger := newTestLogger(t)
	sm := oidc.NewSessionManager([]byte("test-secret-32-characters-long!!"), true, "", logger)

	w := httptest.NewRecorder()
	_ = sm.SetSession(w, "secure@example.com")

	c := findCookie(w.Result().Cookies(), "atlantis_oidc")
	Assert(t, c != nil, "expected atlantis_oidc cookie")
	Assert(t, c.Secure, "expected Secure flag on cookie when secure=true")
}
