// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/core/db (interfaces: Database)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/mock_database.go . Database
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	db "github.com/runatlantis/atlantis/server/core/db"
	command "github.com/runatlantis/atlantis/server/events/command"
	models "github.com/runatlantis/atlantis/server/events/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
	isgomock struct{}
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// AcquirePublicationLease mocks base method.
func (m *MockDatabase) AcquirePublicationLease(arg0 context.Context, arg1 models.PullRequest, arg2 string, arg3 time.Duration) (db.PublicationLease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquirePublicationLease", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(db.PublicationLease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquirePublicationLease indicates an expected call of AcquirePublicationLease.
func (mr *MockDatabaseMockRecorder) AcquirePublicationLease(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquirePublicationLease", reflect.TypeOf((*MockDatabase)(nil).AcquirePublicationLease), arg0, arg1, arg2, arg3)
}

// BeginApplyExecution mocks base method.
func (m *MockDatabase) BeginApplyExecution(pull models.PullRequest, projects []command.ProjectContext, executionID string, mode command.PublicationWriteMode) (models.PullStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginApplyExecution", pull, projects, executionID, mode)
	ret0, _ := ret[0].(models.PullStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginApplyExecution indicates an expected call of BeginApplyExecution.
func (mr *MockDatabaseMockRecorder) BeginApplyExecution(pull, projects, executionID, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginApplyExecution", reflect.TypeOf((*MockDatabase)(nil).BeginApplyExecution), pull, projects, executionID, mode)
}

// BeginPlanGeneration mocks base method.
func (m *MockDatabase) BeginPlanGeneration(pull models.PullRequest, generation string, projects []command.ProjectContext, replace bool, mode command.PublicationWriteMode) (db.PlanGenerationBeginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginPlanGeneration", pull, generation, projects, replace, mode)
	ret0, _ := ret[0].(db.PlanGenerationBeginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginPlanGeneration indicates an expected call of BeginPlanGeneration.
func (mr *MockDatabaseMockRecorder) BeginPlanGeneration(pull, generation, projects, replace, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginPlanGeneration", reflect.TypeOf((*MockDatabase)(nil).BeginPlanGeneration), pull, generation, projects, replace, mode)
}

// BeginPublication mocks base method.
func (m *MockDatabase) BeginPublication(arg0 context.Context, arg1 models.PullRequest, arg2 db.PublicationFence) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginPublication", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeginPublication indicates an expected call of BeginPublication.
func (mr *MockDatabaseMockRecorder) BeginPublication(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginPublication", reflect.TypeOf((*MockDatabase)(nil).BeginPublication), arg0, arg1, arg2)
}

// CheckCommandLock mocks base method.
func (m *MockDatabase) CheckCommandLock(cmdName command.Name) (*command.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCommandLock", cmdName)
	ret0, _ := ret[0].(*command.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCommandLock indicates an expected call of CheckCommandLock.
func (mr *MockDatabaseMockRecorder) CheckCommandLock(cmdName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCommandLock", reflect.TypeOf((*MockDatabase)(nil).CheckCommandLock), cmdName)
}

// Close mocks base method.
func (m *MockDatabase) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDatabaseMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDatabase)(nil).Close))
}

// CompletePublication mocks base method.
func (m *MockDatabase) CompletePublication(arg0 context.Context, arg1 models.PullRequest, arg2 db.PublicationFence) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompletePublication", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompletePublication indicates an expected call of CompletePublication.
func (mr *MockDatabaseMockRecorder) CompletePublication(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompletePublication", reflect.TypeOf((*MockDatabase)(nil).CompletePublication), arg0, arg1, arg2)
}

// DeletePullStatus mocks base method.
func (m *MockDatabase) DeletePullStatus(pull models.PullRequest, mode command.PublicationWriteMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePullStatus", pull, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePullStatus indicates an expected call of DeletePullStatus.
func (mr *MockDatabaseMockRecorder) DeletePullStatus(pull, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePullStatus", reflect.TypeOf((*MockDatabase)(nil).DeletePullStatus), pull, mode)
}

// DiscardPlanStatus mocks base method.
func (m *MockDatabase) DiscardPlanStatus(pull models.PullRequest, expected models.ProjectStatus, mode command.PublicationWriteMode) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscardPlanStatus", pull, expected, mode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiscardPlanStatus indicates an expected call of DiscardPlanStatus.
func (mr *MockDatabaseMockRecorder) DiscardPlanStatus(pull, expected, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscardPlanStatus", reflect.TypeOf((*MockDatabase)(nil).DiscardPlanStatus), pull, expected, mode)
}

// GetLock mocks base method.
func (m *MockDatabase) GetLock(project models.Project, workspace string) (*models.ProjectLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLock", project, workspace)
	ret0, _ := ret[0].(*models.ProjectLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLock indicates an expected call of GetLock.
func (mr *MockDatabaseMockRecorder) GetLock(project, workspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLock", reflect.TypeOf((*MockDatabase)(nil).GetLock), project, workspace)
}

// GetPublicationLease mocks base method.
func (m *MockDatabase) GetPublicationLease(arg0 context.Context, arg1 models.PullRequest) (*db.PublicationLease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicationLease", arg0, arg1)
	ret0, _ := ret[0].(*db.PublicationLease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicationLease indicates an expected call of GetPublicationLease.
func (mr *MockDatabaseMockRecorder) GetPublicationLease(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicationLease", reflect.TypeOf((*MockDatabase)(nil).GetPublicationLease), arg0, arg1)
}

// GetPullStatus mocks base method.
func (m *MockDatabase) GetPullStatus(pull models.PullRequest) (*models.PullStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullStatus", pull)
	ret0, _ := ret[0].(*models.PullStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullStatus indicates an expected call of GetPullStatus.
func (mr *MockDatabaseMockRecorder) GetPullStatus(pull any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullStatus", reflect.TypeOf((*MockDatabase)(nil).GetPullStatus), pull)
}

// List mocks base method.
func (m *MockDatabase) List() ([]models.ProjectLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]models.ProjectLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDatabaseMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDatabase)(nil).List))
}

// LockCommand mocks base method.
func (m *MockDatabase) LockCommand(cmdName command.Name, lockTime time.Time) (*command.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockCommand", cmdName, lockTime)
	ret0, _ := ret[0].(*command.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockCommand indicates an expected call of LockCommand.
func (mr *MockDatabaseMockRecorder) LockCommand(cmdName, lockTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockCommand", reflect.TypeOf((*MockDatabase)(nil).LockCommand), cmdName, lockTime)
}

// Ping mocks base method.
func (m *MockDatabase) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDatabaseMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDatabase)(nil).Ping))
}

// RecoverPublicationLease mocks base method.
func (m *MockDatabase) RecoverPublicationLease(arg0 context.Context, arg1 models.PullRequest, arg2 db.PublicationFence) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecoverPublicationLease", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecoverPublicationLease indicates an expected call of RecoverPublicationLease.
func (mr *MockDatabaseMockRecorder) RecoverPublicationLease(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecoverPublicationLease", reflect.TypeOf((*MockDatabase)(nil).RecoverPublicationLease), arg0, arg1, arg2)
}

// ReleasePublicationLease mocks base method.
func (m *MockDatabase) ReleasePublicationLease(arg0 context.Context, arg1 models.PullRequest, arg2 db.PublicationFence) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleasePublicationLease", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleasePublicationLease indicates an expected call of ReleasePublicationLease.
func (mr *MockDatabaseMockRecorder) ReleasePublicationLease(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleasePublicationLease", reflect.TypeOf((*MockDatabase)(nil).ReleasePublicationLease), arg0, arg1, arg2)
}

// RenewPublicationLease mocks base method.
func (m *MockDatabase) RenewPublicationLease(arg0 context.Context, arg1 models.PullRequest, arg2 db.PublicationFence, arg3 time.Duration) (db.PublicationLease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenewPublicationLease", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(db.PublicationLease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenewPublicationLease indicates an expected call of RenewPublicationLease.
func (mr *MockDatabaseMockRecorder) RenewPublicationLease(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewPublicationLease", reflect.TypeOf((*MockDatabase)(nil).RenewPublicationLease), arg0, arg1, arg2, arg3)
}

// TryLock mocks base method.
func (m *MockDatabase) TryLock(lock models.ProjectLock) (bool, models.ProjectLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryLock", lock)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(models.ProjectLock)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TryLock indicates an expected call of TryLock.
func (mr *MockDatabaseMockRecorder) TryLock(lock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryLock", reflect.TypeOf((*MockDatabase)(nil).TryLock), lock)
}

// Unlock mocks base method.
func (m *MockDatabase) Unlock(project models.Project, workspace string) (*models.ProjectLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", project, workspace)
	ret0, _ := ret[0].(*models.ProjectLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unlock indicates an expected call of Unlock.
func (mr *MockDatabaseMockRecorder) Unlock(project, workspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockDatabase)(nil).Unlock), project, workspace)
}

// UnlockByPull mocks base method.
func (m *MockDatabase) UnlockByPull(repoFullName string, pullNum int) ([]models.ProjectLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockByPull", repoFullName, pullNum)
	ret0, _ := ret[0].([]models.ProjectLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlockByPull indicates an expected call of UnlockByPull.
func (mr *MockDatabaseMockRecorder) UnlockByPull(repoFullName, pullNum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockByPull", reflect.TypeOf((*MockDatabase)(nil).UnlockByPull), repoFullName, pullNum)
}

// UnlockCommand mocks base method.
func (m *MockDatabase) UnlockCommand(cmdName command.Name) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockCommand", cmdName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockCommand indicates an expected call of UnlockCommand.
func (mr *MockDatabaseMockRecorder) UnlockCommand(cmdName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockCommand", reflect.TypeOf((*MockDatabase)(nil).UnlockCommand), cmdName)
}

// UnlockIfOwnedByPull mocks base method.
func (m *MockDatabase) UnlockIfOwnedByPull(project models.Project, workspace string, pullNum int) (*models.ProjectLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockIfOwnedByPull", project, workspace, pullNum)
	ret0, _ := ret[0].(*models.ProjectLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlockIfOwnedByPull indicates an expected call of UnlockIfOwnedByPull.
func (mr *MockDatabaseMockRecorder) UnlockIfOwnedByPull(project, workspace, pullNum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockIfOwnedByPull", reflect.TypeOf((*MockDatabase)(nil).UnlockIfOwnedByPull), project, workspace, pullNum)
}

// UpdateProjectStatus mocks base method.
func (m *MockDatabase) UpdateProjectStatus(pull models.PullRequest, workspace, repoRelDir string, newStatus models.ProjectPlanStatus, mode command.PublicationWriteMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProjectStatus", pull, workspace, repoRelDir, newStatus, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProjectStatus indicates an expected call of UpdateProjectStatus.
func (mr *MockDatabaseMockRecorder) UpdateProjectStatus(pull, workspace, repoRelDir, newStatus, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProjectStatus", reflect.TypeOf((*MockDatabase)(nil).UpdateProjectStatus), pull, workspace, repoRelDir, newStatus, mode)
}

// UpdatePullWithResults mocks base method.
func (m *MockDatabase) UpdatePullWithResults(pull models.PullRequest, newResults []command.ProjectResult, mode command.PublicationWriteMode) (models.PullStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePullWithResults", pull, newResults, mode)
	ret0, _ := ret[0].(models.PullStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePullWithResults indicates an expected call of UpdatePullWithResults.
func (mr *MockDatabaseMockRecorder) UpdatePullWithResults(pull, newResults, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePullWithResults", reflect.TypeOf((*MockDatabase)(nil).UpdatePullWithResults), pull, newResults, mode)
}
