// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	http "net/http"
)

func AnyHttpHeader() http.Header {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(http.Header))(nil)).Elem()))
	var nullValue http.Header
	return nullValue
}

func EqHttpHeader(value http.Header) http.Header {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue http.Header
	return nullValue
}

func NotEqHttpHeader(value http.Header) http.Header {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue http.Header
	return nullValue
}

func HttpHeaderThat(matcher pegomock.ArgumentMatcher) http.Header {
	pegomock.RegisterMatcher(matcher)
	var nullValue http.Header
	return nullValue
}
