// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	models "github.com/runatlantis/atlantis/server/events/models"
)

func AnyModelsParallelCommand() models.ParallelCommand {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(models.ParallelCommand))(nil)).Elem()))
	var nullValue models.ParallelCommand
	return nullValue
}

func EqModelsParallelCommand(value models.ParallelCommand) models.ParallelCommand {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue models.ParallelCommand
	return nullValue
}

func NotEqModelsParallelCommand(value models.ParallelCommand) models.ParallelCommand {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue models.ParallelCommand
	return nullValue
}

func ModelsParallelCommandThat(matcher pegomock.ArgumentMatcher) models.ParallelCommand {
	pegomock.RegisterMatcher(matcher)
	var nullValue models.ParallelCommand
	return nullValue
}
