// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	models "github.com/runatlantis/atlantis/server/events/models"
)

func AnyModelsDeleteLockCommandResult() models.DeleteLockCommandResult {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(models.DeleteLockCommandResult))(nil)).Elem()))
	var nullValue models.DeleteLockCommandResult
	return nullValue
}

func EqModelsDeleteLockCommandResult(value models.DeleteLockCommandResult) models.DeleteLockCommandResult {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue models.DeleteLockCommandResult
	return nullValue
}
