// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	pegomock "github.com/petergtz/pegomock/v3"
	"reflect"

	valid "github.com/runatlantis/atlantis/server/core/config/valid"
)

func AnyValidPostProcessRunOutputOption() valid.PostProcessRunOutputOption {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(valid.PostProcessRunOutputOption))(nil)).Elem()))
	var nullValue valid.PostProcessRunOutputOption
	return nullValue
}

func EqValidPostProcessRunOutputOption(value valid.PostProcessRunOutputOption) valid.PostProcessRunOutputOption {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue valid.PostProcessRunOutputOption
	return nullValue
}

func NotEqValidPostProcessRunOutputOption(value valid.PostProcessRunOutputOption) valid.PostProcessRunOutputOption {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue valid.PostProcessRunOutputOption
	return nullValue
}

func ValidPostProcessRunOutputOptionThat(matcher pegomock.ArgumentMatcher) valid.PostProcessRunOutputOption {
	pegomock.RegisterMatcher(matcher)
	var nullValue valid.PostProcessRunOutputOption
	return nullValue
}
