// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	models "github.com/runatlantis/atlantis/server/events/models"
)

func AnyModelsProjectStatus() models.ProjectStatus {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(models.ProjectStatus))(nil)).Elem()))
	var nullValue models.ProjectStatus
	return nullValue
}

func EqModelsProjectStatus(value models.ProjectStatus) models.ProjectStatus {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue models.ProjectStatus
	return nullValue
}
