// Copyright 2026 The Atlantis Authors
// SPDX-License-Identifier: Apache-2.0

package web_templates

import (
	"fmt"
	"io"
	"sort"
	"time"

	"github.com/runatlantis/atlantis/server/jobs"
)

// BetaDashboardData groups existing dashboard data without accessing storage or VCS.
type BetaDashboardData struct {
	IndexData
	Repositories []BetaRepository
	Total        int // Tracked jobs, including workflow hooks.
}

type BetaRepository struct {
	Name       string
	Workspaces []BetaWorkspace
}

type BetaWorkspace struct {
	Name  string
	Pulls []BetaPull
}

// JobCount includes tracked executions and workflow hooks in this workspace.
func (w BetaWorkspace) JobCount() int {
	count := 0
	for _, pull := range w.Pulls {
		for _, project := range pull.Projects {
			count += len(project.Jobs)
		}
	}
	return count
}

type BetaPull struct {
	ID       string
	URL      string
	Number   int
	Author   string // Known lock owner; unavailable for requests with no lock.
	Projects []BetaProject
}

type BetaProject struct {
	Name string
	Path string
	Jobs []jobs.JobIDInfo
}

// GroupBetaDashboard preserves job and lock URLs generated by the existing router.
// Missing workspace metadata (including workflow hooks) is not assigned to default.
// Only mappings with tracked jobs create groups; locks supply metadata only.
func GroupBetaDashboard(data IndexData) BetaDashboardData {
	result := BetaDashboardData{IndexData: data}
	type requestKey struct {
		repo   string
		number int
	}
	type groupKey struct {
		requestKey
		workspace string
	}
	owners := make(map[requestKey]LockIndexData)
	type requestURL struct {
		url  string
		time time.Time
	}
	urls := make(map[requestKey]requestURL)
	rememberURL := func(key requestKey, value string, updated time.Time) {
		previous, exists := urls[key]
		if value != "" && (!exists || updated.After(previous.time) || (updated.Equal(previous.time) && value < previous.url)) {
			urls[key] = requestURL{value, updated}
		}
	}
	for _, lock := range data.Locks {
		key := requestKey{lock.RepoFullName, lock.PullNum}
		rememberURL(key, lock.PullRequestURL, lock.Time)
		previous, exists := owners[key]
		if lock.LockedBy != "" && (!exists || lock.Time.After(previous.Time) || (lock.Time.Equal(previous.Time) && lock.LockedBy < previous.LockedBy)) {
			owners[key] = lock
		}
	}
	for _, entry := range data.PullToJobMapping {
		key := requestKey{entry.Pull.RepoFullName, entry.Pull.PullNum}
		for _, job := range entry.JobIDInfos {
			rememberURL(key, job.PullRequestURL, job.Time)
		}
	}
	groups := make(map[groupKey]*BetaPull)
	getPull := func(repo, workspace string, number int) *BetaPull {
		request := requestKey{repo, number}
		key := groupKey{request, workspace}
		if groups[key] == nil {
			id := ""
			if number > 0 {
				id = fmt.Sprintf("%s#%d", repo, number)
			}
			groups[key] = &BetaPull{ID: id, URL: urls[request].url, Number: number, Author: owners[request].LockedBy}
		}
		return groups[key]
	}
	for _, entry := range data.PullToJobMapping {
		if len(entry.JobIDInfos) == 0 {
			continue
		}
		pull := getPull(entry.Pull.RepoFullName, entry.Pull.Workspace, entry.Pull.PullNum)
		jobInfos := append([]jobs.JobIDInfo(nil), entry.JobIDInfos...)
		result.Total += len(jobInfos)
		sort.SliceStable(jobInfos, func(i, j int) bool {
			if jobInfos[i].Time.Equal(jobInfos[j].Time) {
				return jobInfos[i].JobID < jobInfos[j].JobID
			}
			return jobInfos[i].Time.After(jobInfos[j].Time)
		})
		pull.Projects = append(pull.Projects, BetaProject{Name: entry.Pull.ProjectName, Path: entry.Pull.Path, Jobs: jobInfos})
	}
	repos := make(map[string]map[string][]BetaPull)
	for key, pull := range groups {
		sort.SliceStable(pull.Projects, func(i, j int) bool {
			if pull.Projects[i].Name == pull.Projects[j].Name {
				return pull.Projects[i].Path < pull.Projects[j].Path
			}
			return pull.Projects[i].Name < pull.Projects[j].Name
		})
		if repos[key.repo] == nil {
			repos[key.repo] = make(map[string][]BetaPull)
		}
		repos[key.repo][key.workspace] = append(repos[key.repo][key.workspace], *pull)
	}
	for name, workspaces := range repos {
		repo := BetaRepository{Name: name}
		for workspace, pulls := range workspaces {
			sort.Slice(pulls, func(i, j int) bool { return pulls[i].Number > pulls[j].Number })
			repo.Workspaces = append(repo.Workspaces, BetaWorkspace{Name: workspace, Pulls: pulls})
		}
		sort.Slice(repo.Workspaces, func(i, j int) bool { return repo.Workspaces[i].Name < repo.Workspaces[j].Name })
		result.Repositories = append(result.Repositories, repo)
	}
	sort.Slice(result.Repositories, func(i, j int) bool { return result.Repositories[i].Name < result.Repositories[j].Name })
	return result
}

type betaDashboardWriter struct{}

func (betaDashboardWriter) Execute(w io.Writer, data any) error {
	index, ok := data.(IndexData)
	if !ok {
		return fmt.Errorf("rendering beta dashboard: expected IndexData, got %T", data)
	}
	return templates.Lookup("beta-dashboard.html.tmpl").Execute(w, GroupBetaDashboard(index))
}

var BetaDashboardTemplate TemplateWriter = betaDashboardWriter{}
