// Copyright 2025 The Atlantis Authors
// SPDX-License-Identifier: Apache-2.0

package models_test

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	. "github.com/petergtz/pegomock/v4"
	"github.com/runatlantis/atlantis/server/core/runtime/models"
	"github.com/runatlantis/atlantis/server/events/command"
	"github.com/runatlantis/atlantis/server/jobs/mocks"
	"github.com/runatlantis/atlantis/server/logging"
	logmocks "github.com/runatlantis/atlantis/server/logging/mocks"
	. "github.com/runatlantis/atlantis/testing"
)

func TestShellCommandRunner_Run(t *testing.T) {
	cases := []struct {
		Command  string
		ExpLines []string
		Environ  map[string]string
	}{
		{
			Command: "echo $HELLO",
			Environ: map[string]string{
				"HELLO": "world",
			},
			ExpLines: []string{"world"},
		},
		{
			Command:  ">&2 echo this is an error",
			ExpLines: []string{"this is an error"},
		},
	}

	for _, c := range cases {
		t.Run(c.Command, func(t *testing.T) {
			RegisterMockTestingT(t)
			log := logmocks.NewMockSimpleLogging()
			When(log.With(Any[string](), Any[any]())).ThenReturn(log)
			ctx := command.ProjectContext{
				Log:        log,
				Workspace:  "default",
				RepoRelDir: ".",
			}
			projectCmdOutputHandler := mocks.NewMockProjectCommandOutputHandler()

			cwd, err := os.Getwd()
			Ok(t, err)
			environ := []string{}
			for k, v := range c.Environ {
				environ = append(environ, fmt.Sprintf("%s=%s", k, v))
			}
			expectedOutput := fmt.Sprintf("%s\n", strings.Join(c.ExpLines, "\n"))

			// Run once with streaming enabled
			runner := models.NewShellCommandRunner(nil, c.Command, environ, cwd, true, projectCmdOutputHandler)
			output, err := runner.Run(ctx)
			Ok(t, err)
			Equals(t, expectedOutput, output)
			for _, line := range c.ExpLines {
				projectCmdOutputHandler.VerifyWasCalledOnce().Send(ctx, line, false)
			}

			log.VerifyWasCalledOnce().With(Eq("duration"), Any[any]())

			// And again with streaming disabled. Everything should be the same except the
			// command output handler should not have received anything

			projectCmdOutputHandler = mocks.NewMockProjectCommandOutputHandler()
			runner = models.NewShellCommandRunner(nil, c.Command, environ, cwd, false, projectCmdOutputHandler)
			output, err = runner.Run(ctx)
			Ok(t, err)
			Equals(t, expectedOutput, output)
			projectCmdOutputHandler.VerifyWasCalled(Never()).Send(Any[command.ProjectContext](), Any[string](), Eq(false))

			log.VerifyWasCalled(Twice()).With(Eq("duration"), Any[any]())
		})
	}
}

func TestShellCommandRunner_RunLongOutputLines(t *testing.T) {
	// Regression test: lines longer than the default bufio.Scanner token
	// size limit (64KiB) must not be silently dropped. Terraform writes
	// its diagnostics to stderr, and some of them (e.g. dependency cycle
	// errors) can exceed 64KiB on a single line.
	//
	// The line is generated by repeatedly doubling a shell variable so
	// the test only depends on POSIX sh built-ins: starting from one
	// character, 17 doublings yield exactly 128KiB.
	longLen := 128 * 1024
	longLine := fmt.Sprintf(`s=x; while [ "${#s}" -lt %d ]; do s=$s$s; done; printf '%%s\n' "$s"`, longLen)
	cases := []struct {
		name    string
		command string
	}{
		{
			name:    "stdout",
			command: longLine,
		},
		{
			name:    "stderr",
			command: fmt.Sprintf("{ %s; } >&2", longLine),
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			RegisterMockTestingT(t)
			log := logmocks.NewMockSimpleLogging()
			When(log.With(Any[string](), Any[any]())).ThenReturn(log)
			ctx := command.ProjectContext{
				Log:        log,
				Workspace:  "default",
				RepoRelDir: ".",
			}
			projectCmdOutputHandler := mocks.NewMockProjectCommandOutputHandler()

			cwd, err := os.Getwd()
			Ok(t, err)

			runner := models.NewShellCommandRunner(nil, c.command, []string{}, cwd, false, projectCmdOutputHandler)
			output, err := runner.Run(ctx)
			Ok(t, err)
			Equals(t, strings.Repeat("x", longLen)+"\n", output)
		})
	}
}

func TestShellCommandRunner_RunFailure(t *testing.T) {
	dir := t.TempDir()
	const script = "printf 'stdout\\n'; printf 'stderr\\n' >&2; exit 7"
	runners := map[string]*models.ShellCommandRunner{
		"shell": models.NewShellCommandRunner(nil, script, nil, dir, false, nil),
		"argv":  models.NewArgvCommandRunner([]string{"sh", "-c", script}, script, nil, dir, false, nil),
	}
	for name, runner := range runners {
		t.Run(name, func(t *testing.T) {
			ctx := command.ProjectContext{Log: logging.NewNoopLogger(t)}
			output, err := runner.Run(ctx)

			exitErr, ok := errors.AsType[*exec.ExitError](err)
			Assert(t, ok, "expected process exit error, got %v", err)
			Equals(t, 7, exitErr.ExitCode())
			// stdout and stderr are read concurrently; their relative order is unspecified.
			lines := strings.Split(strings.TrimSuffix(output, "\n"), "\n")
			slices.Sort(lines)
			Equals(t, []string{"stderr", "stdout"}, lines)
			Assert(t, strings.Contains(err.Error(), dir), "missing working directory context: %v", err)
		})
	}
}

func TestShellCommandRunner_StartFailure(t *testing.T) {
	dir := t.TempDir()
	cases := []struct {
		name, executable, workdir string
	}{
		{"missing executable", filepath.Join(dir, "missing-command"), dir},
		{"missing working directory", "sh", filepath.Join(dir, "missing-dir")},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			ctx := command.ProjectContext{Log: logging.NewNoopLogger(t)}
			runner := models.NewArgvCommandRunner([]string{tc.executable, "-c", "exit 0"}, tc.executable, nil, tc.workdir, false, nil)

			output, err := runner.Run(ctx)

			Equals(t, "", output)
			Assert(t, errors.Is(err, os.ErrNotExist), "expected missing-file error, got %v", err)
			Assert(t, strings.Contains(err.Error(), tc.workdir), "missing working directory context: %v", err)
			Assert(t, strings.Contains(err.Error(), tc.executable), "missing executable context: %v", err)
		})
	}
}
