name: renovate-config

on:
  push:
    paths:
      - '.github/renovate.json5'
    branches:
      - main
      - 'releases-**'
  pull_request:
    paths:
      - '.github/renovate.json5'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      - run: npx --package="renovate@${RENOVATE_VERSION}" -c renovate-config-validator
        env:
          # renovate: datasource=npm depName=renovate
          RENOVATE_VERSION: 43.150.0
