name: renovate-config

on:
  push:
    paths:
      - '.github/renovate.json5'
    branches:
      - main
      - 'releases-**'
  pull_request:
    paths:
      - '.github/renovate.json5'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      - run: npx --package="renovate@${RENOVATE_VERSION}" -c renovate-config-validator
        env:
          # renovate: datasource=npm depName=renovate
          RENOVATE_VERSION: 43.150.0
