name: Triage Issues

on:
  issues:
    types:
      - opened
      - labeled

permissions:
  contents: read

jobs:
  add-needs-triage:
    if: github.event.action == 'opened'
    permissions:
      issues: write
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Add needs-triage label
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['needs-triage']
            })

  remove-needs-triage:
    if: >-
      github.event.action == 'labeled' &&
      contains(fromJSON('["waiting-on-response","wontfix","duplicate","invalid"]'), github.event.label.name)
    permissions:
      issues: write
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Remove needs-triage label
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          script: |
            const labels = context.payload.issue.labels.map(l => l.name);
            if (labels.includes('needs-triage')) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'needs-triage'
              });
            }
